apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: caragence
  labels:
    app: caragence
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caragence
      component: grafana
  template:
    metadata:
      labels:
        app: caragence
        component: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboard
              mountPath: /var/lib/grafana/dashboards
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
        - name: grafana-dashboard
          configMap:
            name: grafana-dashboard
