apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caragence-sqlite-pvc
  namespace: caragence
  labels:
    app: caragence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
