apiVersion: v1
kind: Service
metadata:
  name: caragence-nginx
  namespace: caragence
  labels:
    app: caragence
    component: proxy
spec:
  selector:
    app: caragence
    component: proxy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
