// <auto-generated />
using System;
using CarAgence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarAgence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617191601_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("CarAgence.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jean.dupont@email.com",
                            Nom = "Dupont",
                            Prenom = "Jean",
                            Telephone = "0612345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sophie.martin@email.com",
                            Nom = "Martin",
                            Prenom = "Sophie",
                            Telephone = "0698765432"
                        });
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaysOrigine")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Marques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Renault",
                            PaysOrigine = "France"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Peugeot",
                            PaysOrigine = "France"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "BMW",
                            PaysOrigine = "Allemagne"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Citroën",
                            PaysOrigine = "France"
                        });
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Modele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarqueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarqueId");

                    b.ToTable("Modeles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MarqueId = 1,
                            Nom = "Clio"
                        },
                        new
                        {
                            Id = 2,
                            MarqueId = 1,
                            Nom = "Megane"
                        },
                        new
                        {
                            Id = 3,
                            MarqueId = 2,
                            Nom = "208"
                        },
                        new
                        {
                            Id = 4,
                            MarqueId = 2,
                            Nom = "308"
                        },
                        new
                        {
                            Id = 5,
                            MarqueId = 3,
                            Nom = "Série 3"
                        },
                        new
                        {
                            Id = 6,
                            MarqueId = 4,
                            Nom = "C3"
                        });
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<int>("VoitureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VoitureId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DateDebut = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VoitureId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            DateDebut = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VoitureId = 5
                        });
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Voiture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carburant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModeleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombrePlaces")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TarifJournalier")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Immatriculation")
                        .IsUnique();

                    b.HasIndex("ModeleId");

                    b.ToTable("Voitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Annee = 2022,
                            Carburant = "Essence",
                            Immatriculation = "AB-123-CD",
                            ModeleId = 1,
                            NombrePlaces = 5,
                            TarifJournalier = 35m
                        },
                        new
                        {
                            Id = 2,
                            Annee = 2023,
                            Carburant = "Diesel",
                            Immatriculation = "EF-456-GH",
                            ModeleId = 2,
                            NombrePlaces = 5,
                            TarifJournalier = 45m
                        },
                        new
                        {
                            Id = 3,
                            Annee = 2023,
                            Carburant = "Essence",
                            Immatriculation = "IJ-789-KL",
                            ModeleId = 3,
                            NombrePlaces = 5,
                            TarifJournalier = 38m
                        },
                        new
                        {
                            Id = 4,
                            Annee = 2021,
                            Carburant = "Diesel",
                            Immatriculation = "MN-012-OP",
                            ModeleId = 4,
                            NombrePlaces = 5,
                            TarifJournalier = 55m
                        },
                        new
                        {
                            Id = 5,
                            Annee = 2023,
                            Carburant = "Essence",
                            Immatriculation = "QR-345-ST",
                            ModeleId = 5,
                            NombrePlaces = 5,
                            TarifJournalier = 75m
                        },
                        new
                        {
                            Id = 6,
                            Annee = 2022,
                            Carburant = "Essence",
                            Immatriculation = "UV-678-WX",
                            ModeleId = 6,
                            NombrePlaces = 5,
                            TarifJournalier = 32m
                        });
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Modele", b =>
                {
                    b.HasOne("CarAgence.Domain.Entities.Marque", "Marque")
                        .WithMany("Modeles")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("CarAgence.Domain.Entities.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarAgence.Domain.Entities.Voiture", "Voiture")
                        .WithMany("Reservations")
                        .HasForeignKey("VoitureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Voiture");
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Voiture", b =>
                {
                    b.HasOne("CarAgence.Domain.Entities.Modele", "Modele")
                        .WithMany("Voitures")
                        .HasForeignKey("ModeleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modele");
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Marque", b =>
                {
                    b.Navigation("Modeles");
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Modele", b =>
                {
                    b.Navigation("Voitures");
                });

            modelBuilder.Entity("CarAgence.Domain.Entities.Voiture", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
